---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[perlbrew::default]
      - recipe[perlbrew::profile]
    attributes:
